spring.application.name=vehicles_rental
spring.datasource.url=jdbc:postgresql://localhost:5432/vehicle_rental
spring.datasource.username=postgres
spring.datasource.password=101267

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#verify otp

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=polinapang80@gmail.com
spring.mail.password=buok llsb hzda jrks

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=QW5vdGhlclZlcnlMb25nUmFuZG9tU2VjcmV0S2V5Rm9ySldUX0hTMjU2XzIwMjZfU3ByaW5nQm9vdA==
jwt.expiration=86400000

spring.flyway.enabled=true
