spring.application.name=vehicles_rental

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# ==========================================
# JPA
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ==========================================
# Mail / OTP
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# ==========================================
# JWT
# ==========================================
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000


# ==========================================
# Flyway
# ==========================================
spring.flyway.enabled=true


# ==========================================
# Bakong
# ==========================================
bakong.enabled=false
bakong.api.base-url=${BAKONG_API_BASE_URL}
bakong.api.token=${BAKONG_API_TOKEN}


# ==========================================
# Bakong Merchant
# ==========================================
bakong.merchant.name=${BAKONG_MERCHANT_NAME:Vehicle Rental}
bakong.merchant.city=${BAKONG_MERCHANT_CITY:Phnom Penh}
bakong.merchant.acquiring-bank=${BAKONG_ACQUIRING_BANK:Bakong Tourist}
bakong.merchant.account=${BAKONG_MERCHANT_ACCOUNT:rcn_tp@bkrt}


# ==========================================
# OTP Expiration
# ==========================================
expiration-minutes=10


# ==========================================
# Telegram Bot
# ==========================================
telegram.bot.token=${TELEGRAM_BOT_TOKEN}


# ==========================================
# Cloudinary
# ==========================================
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}


# ==========================================
# Google OAuth2
# ==========================================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email