#spring.application.name=vehicles_rental
#
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/db_vehicle
#spring.datasource.username=postgres
#spring.datasource.password=2008
#spring.datasource.driver-class-name=org.postgresql.Driver
##
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
##
###verify otp
##
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
##spring.mail.username=maopheaktra5@gmail.com
##spring.mail.password=jjkl ndxf nixc tghb
##
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
##
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#jwt.secret=V8mK7qL2xN4pR9sT3wY6uI1oP5aS8dF0gH2jK4lM6nQ9rE7tU3yW5cX1zA6bC8dE0fG2hJ4kL6mN8pQ1rS3vT5xY7zA9bD2fH4jK6mP8sR0uV2wX4yZ6
#jwt.expiration=86400000
##
#spring.flyway.enabled=true
#
##Bakong
#bakong.enabled=false
#
#bakong.api.base-url=https://api-bakong.nbc.gov.kh
#bakong.api.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoiYjE0ZGU3M2JjMTJkNDFjMCJ9LCJpYXQiOjE3ODcyMjE4OTAsImV4cCI6MTc5NDk5Nzg5MH0.9kRKbczfMUOWwbyrv7jPEHX-hncy4om-tHrTzk-1ATY
#
## merchant
#
#bakong.merchant.name=${BAKONG_MERCHANT_NAME:Vehicle Rental}
#bakong.merchant.city=${BAKONG_MERCHANT_CITY:Phnom Penh}
#bakong.merchant.acquiring-bank=${BAKONG_ACQUIRING_BANK:Bakong Tourist}
#bakong.merchant.account=${BAKONG_MERCHANT_ACCOUNT:rcn_tp@bkrt}
#
## 10 minutes
#
#expiration-minutes= 10
#
##Telegram bot
#telegram.bot.token=8913251248:AAF9jOvhlehWuR_1RwJITketiP7-TobJYro
#
##Cloudinary
#cloudinary.cloud-name=ilfvw9fv
#cloudinary.api-key=358235698862256
#cloudinary.api-secret=3AAu1bs0BeJxzZbBVVoFxVrwKKM
